# filepath: /Users/nawrasalabbas/Desktop/flutter_project/happyview3/l10n.yaml
untranslated-messages-file: desiredFileName.txt
# Add other options as needed
arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart